# Vehicle spec
vehicle_max_velocity_mm_s = 4000
trial_max_velocity_mm_s = 1000
acceleration_mm_ss = 300
battery_v_init = 8.3
tire_diameter_mm = 24
gear_motor = 20
gear_wheel = 64
mass_g = 125
wheel_base_mm = 198

# Simulation
desired_velocity_mm_s = 1000
sim_duration_s = 10
pwm_max = 1500

# Motor
motor_R_ohm = 2.83
motor_Kt_Nm_A = 0.00533
motor_kn_rpm_V = 1790
motor_I0_A = 0.0226

# Battery
battery_capacity_Ah = 0.35
battery_v_full = 8.4
battery_v_empty = 6.4
battery_v_min = 6.0
battery_r_internal_ohm = 0.20
battery_i_mcu_A = 0.05

# Drivetrain / resistance
eta_gear = 0.80
resist_F0_N = 0.10
resist_kv_N_per_mps = 0.20
resist_k2_N_per_mps2 = 0.0
